apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-from-scratch
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: application-from-helm
      parameters:
        - name: "replicaCount"
          value: "3"
    path: 03/helm/nginx
    repoURL: https://github.com/Thnnathat/argocd.git
    targetRevision: main 