apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-directory
spec:
  destination:
    namespace: directory
    server: https://kubernetes.default.svc
  project: default
  source:
    # directory:
      # include: '{serviceaccount.yml,service.yml}'
    path: 03/manifest-dir
    repoURL: https://github.com/Thnnathat/argocd.git
    targetRevision: main 